#!/bin/bash

########################################################################
#                                                                      #
# copy-path                                                            #
#                                                                      #
# Copyright (C) 2020 PJ Singh <psingh.cubic@gmail.com>                 #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# This file is part of Cubic - Custom Ubuntu ISO Creator.              #
#                                                                      #
# Cubic is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Cubic is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Cubic. If not, see <http://www.gnu.org/licenses/>.        #
#                                                                      #
########################################################################

# Copy a file or directory for Cubic.

########################################################################
# Constants
########################################################################

CUSTOM_DISK_DIRECTORY="custom-disk"
CUSTOM_ROOT_DIRECTORY="custom-root"
CUSTOM_LIVE_DIRECTORY="custom-live"
BACKUP_ROOT_DIRECTORY="backup-root"
BACKUP_LIVE_DIRECTORY="backup-live"

########################################################################
# Arguments
########################################################################

program=${0}
number_arguments=${#}
source_file_path=${1}
target_file_path=${2}
user=${3}

# echo "program..................... ${program}"
# echo "number of arguments......... ${number_arguments}"
# echo "source file path............ ${source_file_path}"
# echo "target file path............ ${target_file_path}"
# echo "user........................ ${user}"

########################################################################
# Command
########################################################################

# As a precaution, limit the paths that this command may be executed on.
# Require the target path to contain the directory name as a path segment.
if [[ "$target_file_path" != *"$CUSTOM_DISK_DIRECTORY"* && \
      "$target_file_path" != *"$CUSTOM_ROOT_DIRECTORY"* && \
      "$target_file_path" != *"$CUSTOM_LIVE_DIRECTORY"* && \
      "$target_file_path" != *"$BACKUP_ROOT_DIRECTORY"* && \
      "$target_file_path" != *"$BACKUP_LIVE_DIRECTORY"* ]]; then
    if [[ -n "$user" ]]; then
        echo "Error. Unable to copy ${source_file_path} to ${target_file_path} for ${user}."
    else
        echo "Error. Unable to copy ${source_file_path} to ${target_file_path}."
    fi
    exit 1
fi

# Ensure the target parent directories exist.
directory_path="$(dirname -- "$target_file_path")"
sudo mkdir --parents -- "$directory_path"

# Run rsync, capture its exit code, and stop on rsync failure. The
# "--inplace" option updates destination files in-place. If a user was
# supplied, change ownership.
if [[ -n "$user" ]]; then
    sudo rsync            \
    --archive             \
    --inplace             \
    --info=progress2      \
    --chown="$user:$user" \
    --owner               \
    --group               \
    "${source_file_path}" "${target_file_path}"
else
    sudo rsync            \
    --archive             \
    --inplace             \
    --info=progress2      \
    "${source_file_path}" "${target_file_path}"
fi

# Use echo $? to check the error status.
# http://www.tldp.org/LDP/abs/html/exitcodes.html
exit_code=$?

exit "$exit_code"

