#!/bin/bash

########################################################################
#                                                                      #
# delete-path                                                          #
#                                                                      #
# Copyright (C) 2020 PJ Singh <psingh.cubic@gmail.com>                 #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# This file is part of Cubic - Custom Ubuntu ISO Creator.              #
#                                                                      #
# Cubic is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Cubic is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Cubic. If not, see <http://www.gnu.org/licenses/>.        #
#                                                                      #
########################################################################

# Delete a file or directory for Cubic.

########################################################################
# Constants
########################################################################

CUSTOM_DISK_DIRECTORY="custom-disk"
CUSTOM_ROOT_DIRECTORY="custom-root"
CUSTOM_LIVE_DIRECTORY="custom-live"
BACKUP_ROOT_DIRECTORY="backup-root"
BACKUP_LIVE_DIRECTORY="backup-live"
IMAGE_FILE_NAME="partition-[1-9].img"

########################################################################
# Arguments
########################################################################

program=${0}
number_arguments=${#}
target_file_path=${1}

# echo "program..................... ${program}"
# echo "number of arguments......... ${number_arguments}"
# echo "target file path............ ${target_file_path}"

########################################################################
# Command
########################################################################

# As a precaution, limit the paths that this command may be executed on.
# Require the target path to contain the directory name as a path segment.
if [[ "$target_file_path" != *"$CUSTOM_DISK_DIRECTORY"* && \
      "$target_file_path" != *"$CUSTOM_ROOT_DIRECTORY"* && \
      "$target_file_path" != *"$CUSTOM_LIVE_DIRECTORY"* && \
      "$target_file_path" != *"$BACKUP_ROOT_DIRECTORY"* && \
      "$target_file_path" != *"$BACKUP_LIVE_DIRECTORY"* && \
      "$target_file_path" != *$IMAGE_FILE_NAME ]]; then
    echo "Error. Unable to delete ${target_file_path}."
    exit 1
fi

rm -rf "${target_file_path}"

